import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./(components)/Nav";
import Footer from "./(components)/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className = "flex flex-col h-screen max-h-screen">
          <Nav/>
          <div className = "flex-grow overflow-y-auto">
            {children}
          <Footer/>
          </div> 
        </div>
      </body>
    </html>
  );
}
